In [1]:
import numpy as np

In [12]:
"""Problem Statement: Given a list of numbers, write a function that converts the list to a NumPy array, 
reshapes it into a 2D array with a specified number of columns, and returns the reshaped array."""

def reshape(lst,num_col):
    np_array = np.array(lst)
    if len(lst) % num_col != 0:
        raise ValueError("can't reshape")
    num_rows = len(lst) // num_col
    reshaped_array = np_array.reshape(num_rows,num_col)
    return reshaped_array
lst = [1,2,3,4,5,6,7,8,9,10]
num_col = 5
print(reshape(lst,num_col))
    
    

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [4]:
"""2.Write a function that takes a NumPy array of numerical data and returns 
a dictionary containing the mean, median, standard deviation, and variance of the array."""

def stats(my_array):
    my_dict = {
        "mean":np.mean(my_array),
        "median":np.median(my_array),
        "std": np.std(my_array),
        "var":np.var(my_array)}
    return my_dict
my_array = [2,4,6,3,5,7]
print(stats(my_array))
        

{'mean': 4.5, 'median': 4.5, 'std': 1.707825127659933, 'var': 2.9166666666666665}


In [15]:
"""3.Create a function that takes two NumPy arrays of the same shape and returns 
a new array that contains the element-wise product of the two arrays. Handle cases where the arrays may contain zeros."""
import numpy as np
def product_array(arr1,arr2):
    if arr1.shape != arr2.shape:
        raise ValueError("not matching")
    return arr1 * arr2
arr1=np.array([1,2,3,4])
arr2=np.array([1,2,3,4])
print(product_array(arr1,arr2))
        

[ 1  4  9 16]


In [24]:
"""4. Given a NumPy array of integers, write a function that returns a 
new array containing only the even numbers from the original array. Use NumPy’s masking capabilities to achieve this."""
"""
def filter_even_numbers(arr):
    new_arr = []
    for i in arr:
        if i % 2 == 0:
            new_arr.append(i)
    return new_arr
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(filter_even_numbers(arr))"""

def filter_even_numbers(original_arr):
    mask = (original_arr % 2 == 0)
    even_num = original_arr[mask]
    return even_num
original_arr = np.array([10,25,35,40,50])
even_arr = filter_even_numbers(original_arr)
print("original array : ", original_arr)
print("even array : ", even_arr)


original array :  [10 25 35 40 50]
even array :  [10 40 50]


In [29]:
""" 5.Write a function that takes two 2D NumPy arrays (matrices) and computes their dot product. Ensure that the function checks the dimensions of 
the matrices to confirm that the dot product can be performed."""

def matrix_dot_product(arr1,arr2):
    return np.dot(arr1,arr2)
arr1 = np.array([[1,2,3],[5,6,7]])
arr2 = np.array([[1,3,4],[6,2,1],[2,3,4]])
print(matrix_dot_product(arr1,arr2))

[[19 16 18]
 [55 48 54]]


In [43]:
#6
def concatenate_arrays(array_list, axis=0):
    return np.concatenate(array_list, axis=axis)

arr1 = np.array([[1, 2, 3], 
                  [4, 5, 6]])

arr2 = np.array([[7, 8, 9], 
                  [10, 11, 12]])

arr3 = np.array([[13, 14, 15], 
                  [16, 17, 18]])

array_list = [arr1, arr2, arr3]

result = concatenate_arrays(array_list)

print("Concatenated Array along axis 0:")
print(result)
result_axis1 = concatenate_arrays(array_list, axis=1)

print("\nConcatenated Array along axis 1:")
print(result_axis1)


Concatenated Array along axis 0:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]

Concatenated Array along axis 1:
[[ 1  2  3  7  8  9 13 14 15]
 [ 4  5  6 10 11 12 16 17 18]]


In [42]:
#7
def sorted_array_with_indices(arr):  
    indices = np.argsort(arr)
    sorted_arr = arr[indices]
    return sorted_arr, indices
original_arr = np.array([5, 2, 8, 1, 9])
sorted_arr, indices = sorted_array_with_indices(original_arr)

print("Original Array:", original_arr)
print("Sorted Array:", sorted_arr)
print("Indices that would sort the original array:", indices)


Original Array: [5 2 8 1 9]
Sorted Array: [1 2 5 8 9]
Indices that would sort the original array: [3 1 0 2 4]


In [41]:
#8
def reshape_and_transpose(arr, dim1, dim2, dim3):
    if arr.size != dim1 * dim2 * dim3:
        raise ValueError("Cannot reshape array of size {} into shape ({}, {}, {})".format(arr.size, dim1, dim2, dim3))

    reshaped_array = arr.reshape((dim1, dim2, dim3))
    transposed_array = reshaped_array.transpose()  
    return transposed_array
original_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
dim1, dim2, dim3 = 2, 3, 2  

try:
    result = reshape_and_transpose(original_array, dim1, dim2, dim3)
    print("Transposed 3D Array:")
    print(result)
except ValueError as e:
    print(e)


Transposed 3D Array:
[[[ 1  7]
  [ 3  9]
  [ 5 11]]

 [[ 2  8]
  [ 4 10]
  [ 6 12]]]


In [39]:
#9
from typing import Tuple

def unique_values_and_counts(data: np.ndarray) -> Tuple[np.ndarray, np.ndarray]:
    unique_values, counts = np.unique(data, return_counts=True)
    return unique_values, counts

data = np.array([1, 2, 2, 3, 4, 4, 4, 5, 5])
unique_vals, counts = unique_values_and_counts(data)

print("Unique values:", unique_vals)
print("Counts:", counts)


Unique values: [1 2 3 4 5]
Counts: [1 2 1 3 2]


In [40]:
#10
def add_1d_to_2d(array_2d: np.ndarray, array_1d: np.ndarray) -> np.ndarray:
    if array_1d.ndim != 1:
        raise ValueError("The second argument must be a 1D array.")
    result = array_2d + array_1d
    return result

array_2d = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

array_1d = np.array([10, 20, 30])

result_array = add_1d_to_2d(array_2d, array_1d)
print("Resulting Array:\n", result_array)


Resulting Array:
 [[11 22 33]
 [14 25 36]
 [17 28 39]]
